import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "sign-up",
    description: "Generated by create next app",
};
export default function Register() {
    return (
        <>
            <h1>register</h1>
        </>
    )
}