import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "sign-in",
    description: "Generated by create next app",
};
export default function Login() {
    return (
        <>
            <h1>login</h1>
        </>
    )
}