import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "profile",
    description: "Generated by create next app",
};

export default function Perfil() {
    return (
        <>
            <h1>Perfil</h1>
        </>
    )
}