import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Shopping Cart",
    description: "Generated by create next app",
};

export default function MyCart() {
    return (
        <>
            <h1>Carrinho</h1>
        </>
    )
}